version: '2'
services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - random_walker
    links:
      - random_walker:random_walker
  random_walker:
    restart: always
    build: ./web
    expose:
      - "8000"
    tty: true
    depends_on:
      - postgis
  postgis:
    restart: always
    build: ./postgis
    ports:
      - "5432:5432"